sudo: false
language: scala

scala_version_212: &scala_version_212 "2.12.14"
scala_version_213: &scala_version_213 "2.13.1"

jdk:
  - openjdk11

before_install:
  - git fetch --tags
  - export PATH=${PATH}:./vendor/bundle

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    -
      name: test 2.13
      scala: *scala_version_213
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: test 2.12
      scala: *scala_version_212
      script: sbt ++$TRAVIS_SCALA_VERSION test
    -
      name: mima
      script: sbt +mimaReportBinaryIssues
    -
      name: docs
      scala: *scala_version_212
      install:
        - rvm use 2.6.5 --install --fuzzy
        - gem install jekyll -v 4
      script: sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite
    # run ci-release only if previous stages passed
    - stage: release
      name: release
      script:
        - sbt ci-release
    - stage: release
      name: microsite
      scala: *scala_version_212
      install:
        - rvm use 2.6.5 --install --fuzzy
        - gem install jekyll -v 4
      script: sbt ++$TRAVIS_SCALA_VERSION docs/publishMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
